services:
  features:
    image: features
    build:
      context: .
      dockerfile: Features/Dockerfile
  Postgres:
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb2